name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        run: |
          sudo snap install doctl

      - name: Debug DO_API_TOKEN
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          echo "DO_API_TOKEN is set: ${DO_API_TOKEN:+set}"

      - name: Authenticate with DigitalOcean
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          doctl auth init -t "$DO_API_TOKEN"
          sudo snap connect doctl:dot-docker
          sudo doctl registry login

      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 -t registry.digitalocean.com/email-newsletter/email:latest .
          docker push registry.digitalocean.com/email-newsletter/email:latest

      - name: Deploy to Droplet
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key "$SSH_USER@$DROPLET_IP" 'bash /root/update.sh'
          rm private_key
